package com.wx.springbootdemo.mapper;

import com.wx.springbootdemo.entity.ProductGoods;

import java.util.List;
import java.util.Map;

public interface ProductGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_product_goods
     *
     * @mbg.generated Fri Jun 08 08:55:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_product_goods
     *
     * @mbg.generated Fri Jun 08 08:55:59 CST 2018
     */
    int insert(ProductGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_product_goods
     *
     * @mbg.generated Fri Jun 08 08:55:59 CST 2018
     */
    int insertSelective(ProductGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_product_goods
     *
     * @mbg.generated Fri Jun 08 08:55:59 CST 2018
     */
    ProductGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_product_goods
     *
     * @mbg.generated Fri Jun 08 08:55:59 CST 2018
     */
    int updateByPrimaryKeySelective(ProductGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_product_goods
     *
     * @mbg.generated Fri Jun 08 08:55:59 CST 2018
     */
    int updateByPrimaryKey(ProductGoods record);

    /**
     * 查询所有的产品(已发布、未发布)
     * @param param
     * @return
     */
    List<ProductGoods> selectProductGoodsList(Map param);

    /**
     * 查询已发布的商品
     * @param param
     * @return
     */
    List<Map> selectProductGoodsPublishedList(Map param);
}