package com.wx.springbootdemo.mapper;

import com.wx.springbootdemo.entity.UserInfoExt;

import java.util.Map;

public interface UserInfoExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_ext
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_ext
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    int insert(UserInfoExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_ext
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    int insertSelective(UserInfoExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_ext
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    UserInfoExt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_ext
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    int updateByPrimaryKeySelective(UserInfoExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_ext
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    int updateByPrimaryKey(UserInfoExt record);

    UserInfoExt selectByUsername(String username);

    int deleteUserInfoExtByUID(Integer uid);
    int updateUserInfoExtByUID(Map param);
    Map selectUserInfoByUID(Integer uid);
}