package com.wx.springbootdemo.mapper;

import com.wx.springbootdemo.entity.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 21 17:18:49 CST 2018
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 21 17:18:49 CST 2018
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 21 17:18:49 CST 2018
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 21 17:18:49 CST 2018
     */
    UserInfo selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 21 17:18:49 CST 2018
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 21 17:18:49 CST 2018
     */
    int updateByPrimaryKey(UserInfo record);

    UserInfo selectByUsername(String username);

    int selectUserCount(Map param);
    List<Map> selectUserList(Map param);

    int deleteUserroleByUID(Integer uid);
    int saveUserroleList(@Param("userroleList") List<Map> userroleList);
}