package com.wx.springbootdemo.entity;

import java.util.Date;

public class ProductGoodsPublish {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_s_product_goods_publish.id
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_s_product_goods_publish.state
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_s_product_goods_publish.type
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_s_product_goods_publish.goods_id
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_s_product_goods_publish.publish_code
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    private String publishCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_s_product_goods_publish.create_user_id
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_s_product_goods_publish.create_time
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_s_product_goods_publish.update_time
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_s_product_goods_publish.id
     *
     * @return the value of t_s_product_goods_publish.id
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_s_product_goods_publish.id
     *
     * @param id the value for t_s_product_goods_publish.id
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_s_product_goods_publish.state
     *
     * @return the value of t_s_product_goods_publish.state
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_s_product_goods_publish.state
     *
     * @param state the value for t_s_product_goods_publish.state
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_s_product_goods_publish.type
     *
     * @return the value of t_s_product_goods_publish.type
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_s_product_goods_publish.type
     *
     * @param type the value for t_s_product_goods_publish.type
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_s_product_goods_publish.goods_id
     *
     * @return the value of t_s_product_goods_publish.goods_id
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_s_product_goods_publish.goods_id
     *
     * @param goodsId the value for t_s_product_goods_publish.goods_id
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_s_product_goods_publish.publish_code
     *
     * @return the value of t_s_product_goods_publish.publish_code
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public String getPublishCode() {
        return publishCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_s_product_goods_publish.publish_code
     *
     * @param publishCode the value for t_s_product_goods_publish.publish_code
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public void setPublishCode(String publishCode) {
        this.publishCode = publishCode == null ? null : publishCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_s_product_goods_publish.create_user_id
     *
     * @return the value of t_s_product_goods_publish.create_user_id
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_s_product_goods_publish.create_user_id
     *
     * @param createUserId the value for t_s_product_goods_publish.create_user_id
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_s_product_goods_publish.create_time
     *
     * @return the value of t_s_product_goods_publish.create_time
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_s_product_goods_publish.create_time
     *
     * @param createTime the value for t_s_product_goods_publish.create_time
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_s_product_goods_publish.update_time
     *
     * @return the value of t_s_product_goods_publish.update_time
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_s_product_goods_publish.update_time
     *
     * @param updateTime the value for t_s_product_goods_publish.update_time
     *
     * @mbg.generated Fri Jun 08 08:56:41 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}