package com.wx.springbootdemo.entity;

import java.io.Serializable;
import java.util.Date;

public class UserInfoExt implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_ext.id
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_ext.uid
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_ext.username
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_ext.name
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_ext.avatar
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_ext.state
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_ext.create_time
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_ext.update_time
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    private Date updateTime;

    public UserInfoExt() {
    }

    public UserInfoExt(Integer uid, String username, String name, String avatar, Byte state, Date createTime, Date updateTime) {
        this.uid = uid;
        this.username = username;
        this.name = name;
        this.avatar = avatar;
        this.state = state;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_ext.id
     *
     * @return the value of user_info_ext.id
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_ext.id
     *
     * @param id the value for user_info_ext.id
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_ext.uid
     *
     * @return the value of user_info_ext.uid
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_ext.uid
     *
     * @param uid the value for user_info_ext.uid
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_ext.username
     *
     * @return the value of user_info_ext.username
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_ext.username
     *
     * @param username the value for user_info_ext.username
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_ext.name
     *
     * @return the value of user_info_ext.name
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_ext.name
     *
     * @param name the value for user_info_ext.name
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_ext.avatar
     *
     * @return the value of user_info_ext.avatar
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_ext.avatar
     *
     * @param avatar the value for user_info_ext.avatar
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_ext.state
     *
     * @return the value of user_info_ext.state
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_ext.state
     *
     * @param state the value for user_info_ext.state
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_ext.create_time
     *
     * @return the value of user_info_ext.create_time
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_ext.create_time
     *
     * @param createTime the value for user_info_ext.create_time
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_ext.update_time
     *
     * @return the value of user_info_ext.update_time
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_ext.update_time
     *
     * @param updateTime the value for user_info_ext.update_time
     *
     * @mbg.generated Fri Mar 30 21:51:49 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}